export default {

  LOAD_SECTIONS_REQUEST : 'LOAD_SECTIONS_REQUEST',
  LOAD_SECTIONS_SUCCESS : 'LOAD_SECTIONS_SUCCESS',
  LOAD_SECTIONS_FAILED : 'LOAD_SECTIONS_FAILED',

  ADD_SECTION_SUCCESS : 'ADD_SECTION_SUCCESS',
  ADD_SECTION_REQUEST : 'ADD_SECTION_REQUEST',
  ADD_SECTION_FAILED : 'ADD_SECTION_FAILED',

  CREATE_TODO_REQUEST: 'CREATE_TODO_REQUEST',
  CREATE_TODO_SUCCESS: 'CREATE_TODO_SUCCESS',
  CREATE_TODO_FAILED: 'CREATE_TODO_FAILED',

  // plant constants
  ADD_SENSOR_REQUEST: 'ADD_SENSOR_REQUEST',
  ADD_SENSOR_SUCCESS: 'ADD_SENSOR_SUCCESS',
  ADD_SENSOR_FAILED: 'ADD_SENSOR_FAILED',

  ADD_SWITCH_REQUEST: 'ADD_SWITCH_REQUEST',
  ADD_SWITCH_SUCCESS: 'ADD_SWITCH_SUCCESS',
  ADD_SWITCH_FAILED: 'ADD_SWITCH_FAILED',

  LOAD_SENSORS_REQUEST : 'LOAD_SENSORS_REQUEST',
  LOAD_SENSORS_SUCCESS : 'LOAD_SENSORS_SUCCESS',
  LOAD_SENSORS_FAILED : 'LOAD_SENSORS_FAILED',

  LOAD_SWITCHES_REQUEST : 'LOAD_SWITCHES_REQUEST',
  LOAD_SWITCHES_SUCCESS : 'LOAD_SWITCHES_SUCCESS',
  LOAD_SWITCHES_FAILED : 'LOAD_SWITCHES_FAILED',

  TOGGLE_SWITCHES_REQUEST : 'TOGGLE_SWITCHES_REQUEST',
  TOGGLE_SWITCHES_SUCCESS : 'TOGGLE_SWITCHES_SUCCESS',
  TOGGLE_SWITCHES_FAILED : 'TOGGLE_SWITCHES_FAILED',

}
